service: sls-data-service

custom:
  MONGO_URI: ${env:MONGO_URI}

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    MONGO_URI: ${self:custom.MONGO_URI}

functions:
  createPersona:
    handler: src/handler.createPersona
    events:
      - http:
          path: personas
          method: post
  findPersona:
    handler: src/handler.findPersona
    events:
      - http:
          path: personas/{id}
          method: get

  updatePersona:
    handler: src/handler.updatePersona
    events:
      - http:
          path: personas/{id}
          method: put

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
