service: sls-data-service

provider:
  name: aws
  runtime: nodejs8.10

functions:
  createPersona:
    handler: src/handler.createPersona
    events:
      - http:
          path: personas
          method: post

  updatePersona:
    handler: src/handler.updatePersona
    events:
      - http:
          path: personas/{id}
          method: put

plugins:
  - serverless-offline
